# Generated by Django 2.1.4 on 2018-12-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('meta_description', models.CharField(max_length=1500)),
                ('meta_title', models.CharField(max_length=250)),
            ],
        ),
    ]
